version: "3.9"
services:
  accessbot:
    build: .
    environment:
      - SLACK_TOKEN=slack-token
      - SDM_ADMINS="@slack-handle1 @slack-handle2" # use space for config multiple slack handles 
      - SDM_ADMIN_TIMEOUT=30 # optional, default = 30
      - SDM_API_ACCESS_KEY=sdm-api-acess-key
      - SDM_API_SECRET_KEY=sdm-api-secret-key
      - SDM_AUTO_APPROVE_ALL=false # optional, default = false
